global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'component', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h

    - match:
        component: kafka
      receiver: 'kafka-team'
      group_wait: 30s

    - match:
        component: flink
      receiver: 'flink-team'
      group_wait: 30s

    - match:
        component: backend
      receiver: 'backend-team'
      group_wait: 30s

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['component', 'alertname']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['job']

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/critical'
        send_resolved: true

  - name: 'kafka-team'
    webhook_configs:
      - url: 'http://localhost:5001/kafka'
        send_resolved: true

  - name: 'flink-team'
    webhook_configs:
      - url: 'http://localhost:5001/flink'
        send_resolved: true

  - name: 'backend-team'
    webhook_configs:
      - url: 'http://localhost:5001/backend'
        send_resolved: true
